:PROPERTIES:
:ID:       6a6c667b-a9d0-4ce1-a6b6-9143b4fdfe88
:END:
#+title: Spiritual fasting
#+filetags: :Humility:Discipline:Fasting:Christianity:

* Spiriual fasting in Christianity
Fasting is the act of _abstaining from food_ and or pleasures besides food, such as social media, gaming, or for married couples, sex.

Followers of Christ fast as a spiritual *discipline*. The act of fasting *cuts off the distractions* of the world, so that we can _focus solely on God_. It requires discipline and _reliace on God_'s power to fast, we put our carnal desires aside and put our trust fully on him, *offering our pleasures as an offering* pleasing to God. [[id:e0d7916b-9303-4a9b-a926-f3d1e75ffdcd][More on biblical reasons to fast.]]

** Types of fasts
*** Food
**** Full fast
Abstaining from all foods and juices, only allowing water to enter the body.
**** Partial fast
Abstaining from certain food groups.
**** Intermitten fast
Rejecting food for a certain time period.
*** Other pleasures (self explanatory)
**** Social media fast
**** Gaming
**** Video entertainment
**** etc...
