:PROPERTIES:
:ID:       4327605e-d9c0-4e9d-9805-ed2a87ef66d7
:END:
#+title: True repentance
#+filetags: :Temptation:Conscience:Grief:Repentance:Christianity:

* Repentance
Repentance is the feeling of regret for one's past actions, and a change of mind (metanoia) commited to changing your behaviour. It involves a sincere desire to turn away from your sins and make amends.

** Supernatural grief
#+begin_quote
"Mourning is the conditional pain of a soul on fire."
~ St. John Climacus
#+end_quote

Repentance *must* entail _supernatural grief_ and *inner sorrow* over its sins. Supernatural grief is the affliction of the heart from _God's grace_. This compunction must be a yearning for _reconciliation with God_. We must learn to nurture this pain of heart by listening to our _conscience_ and using our free will to resist temptation. It is in the moment of *using our free will* to combat temptation that the grace of God (supernatural grief) fall on us, and grows within us. If one tries to *resist temptation* and find it *impossible*, it is a clear sign of a _neglection of our conscience in our life_.

* References
https://www.youtube.com/watch?v=MsrMvsqT1Fc
